# Draw phylogenetic trees generated by IQ-Tree using ggtree

library(ape)
library(tidyverse)
library(ggtree)
library(treeio)
library(magrittr)
library(rcartocolor)

library(ggexpand)
library(Cairo)

treefile <- file.choose()
tree <- read.iqtree(treefile)

tree_tbl <- as_tibble(tree)
Clade3_nodes <- dplyr::filter(tree_tbl, grepl('LOAG|Bm|OVO|Ovo|Tcan',label))
Clade4_nodes <- dplyr::filter(tree_tbl, grepl('PTRK|RSKR|L596|SRAE|Sst|SVE',label))
Clade5_nodes <- dplyr::filter(tree_tbl, grepl('Acey|Cbr|Cel|HCON|Necator|PPA',label))

grp <- list (Clade3 = Clade3_nodes$node,
             Clade4 = Clade4_nodes$node,
             Clade5 = Clade5_nodes$node)

cladecolors <- c("Clade3" = "darkorchid",
                 "Clade4" = "coral",
                 "Clade5" = "darkblue")

p <- ggtree(tree, layout = "circular") +
  geom_tiplab(size = 1.75, hjust = -.05) 

p2 <- groupOTU(p, grp, 'Clade') + aes(color = Clade) +
  scale_color_manual(values = cladecolors)

ggsave(plot = p2,
       filename ="2026-0404_nematode_sGCs_circular.pdf",
       width = 5, height = 5)

